DESCRIPTION_FIELD_NAME = 'description'
FULL_AMOUNT_FIELD_NAME = 'full_amount'
NAME_FIELD_NAME = 'name'
INVESTED_AMOUNT_FIELD_NAME = 'invested_amount'
CLOSE_DATE_FIELD_NAME = 'close_date'
FIELD_MAX_LENGTH = 100
FIELD_MIN_LENGTH = 1
FULL_AMOUNT_MIN_VALUE = 0
